urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/', include(admin.site.urls)),
)

# Auth
urlpatterns += patterns('',
    (r'^accounts/login/$',  'django.contrib.auth.views.login'),
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout'),
    (r'^accounts/register/$', 'darkfraud.blog.views.register'),
    (r'^accounts/profile/$', 'darkfraud.blog.views.profile'),
)

# Blog
urlpatterns += patterns('',
    (r'^$', 'darkfraud.blog.views.home'),
    (r'^category/(?P<slug>[-\w]+)/$', 'darkfraud.blog.views.category'),
    (r'^tag/(?P<slug>[-\w]+)/$', 'darkfraud.blog.views.tag'),
    (r'^post/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$', 'darkfraud.blog.views.post'),
    (r'^arhive/(?P<year>\d{4})/(?P<month>\d{2})/$', 'darkfraud.blog.views.arhive'),
    (r'^search/$', 'darkfraud.blog.views.search'),
)

#Page
urlpatterns += patterns('',
    (r'^page/(?P<id>\d)/$',  'darkfraud.pages.views.page'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )

blog/models.py
# -*- coding: utf-8 -*-
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.db.models.signals import post_save, pre_delete
from darkfraud.utils import *

class Category(models.Model):
    title = models.CharField(max_length = 250, verbose_name = 'Название')
    slug = models.SlugField(unique=True, verbose_name = 'Арес')
    description = models.TextField(verbose_name = 'Описание')
    
    class Meta:
        ordering = ['title']
        verbose_name_plural = 'Категории'
        verbose_name = 'Категория'
    
    def __unicode__(self):
        return self.title

class Tag(models.Model):
    title = models.CharField(max_length = 250, verbose_name = 'Название')
    slug = models.SlugField(unique=True, verbose_name = 'Арес')
    
    class Meta():
        ordering = ['title']
        verbose_name_plural = 'Тэги'
        verbose_name = 'Тэг'
    
    def __unicode__(self):
        return self.title

class Post(models.Model):
    STATUS_CHOICES = (
        (1, 'Открыто'),
        (2, 'Закрыто'),
    )
    status = models.IntegerField(choices=STATUS_CHOICES, default=1, verbose_name = 'Статус')
    title = models.CharField(max_length = 250, verbose_name = 'Название')
    pub_date = models.DateTimeField(default = datetime.datetime.now, verbose_name = 'Дата')
    slug = models.SlugField(unique_for_date = 'pub_date', verbose_name = 'Арес')
    content = models.TextField(verbose_name = 'Контент')
    author = models.ForeignKey(User, verbose_name ='Автор')
    categories = models.ManyToManyField(Category)#, verbose_name ='Категории')
    tags = models.ManyToManyField(Tag)#, verbose_name ='Теги')
    enable_comments = models.BooleanField(default = True, verbose_name ='Позволить коментировать')
    
    class Meta():
        ordering = ['-pub_date']
        verbose_name_plural = 'Посты'
        verbose_name = 'Пост'
    
    def __unicode__(self):
        return self.title

class Comment(models.Model):
    STATUS_CHOICES = (
        (1, 'Открыто'),
        (2, 'Закрыто'),
    )
    status = models.IntegerField(choices = STATUS_CHOICES, default = 2, verbose_name ='Статус')
    comment = models.TextField(verbose_name = 'Коментарий')
    author = models.ForeignKey(User, verbose_name = 'Автор')
    post = models.ForeignKey(Post, verbose_name = 'Пост')
    pub_date = models.DateTimeField(default = datetime.datetime.now, verbose_name='Дата')
    
    class Meta:
        ordering = ['-pub_date']
        verbose_name_plural = 'Коментарий'
        verbose_name = 'Коментарий'
    
    def __unicode__(self):
        return self.post.title

class Image(models.Model):
    title = models.CharField(max_length = 250, verbose_name = 'Название')
    image = models.ImageField(upload_to = 'images/Blog/', verbose_name = 'Изображение')
    
    class Meta:
        verbose_name_plural = 'Изображения'
        verbose_name = 'Изобрвжение'
    
    def __unicode__(self):
        return self.title
    
    def get_thumbnail_html(self):
        html = '<a class="image-picker" href="%s"><img src="%s" alt="%s"/></a>'
        return html % (self.image.url, get_thumbnail_url(self.image.url), self.title)
    get_thumbnail_html.short_description = 'Изображение'
    get_thumbnail_html.allow_tags = True

def post_save_handler(sender, **kwargs):
    create_thumbnail(kwargs['instance'].image.path)
post_save.connect(post_save_handler, sender=Image)

def pre_delete_handler(sender, **kwargs):
    delete_thumbnail(kwargs['instance'].image.path)
pre_delete.connect(pre_delete_handler, sender=Image)

blog/views.py
# -*- coding: utf-8 -*-
import datetime, time
from django.core.mail import send_mail
from django.db.models import Q
from django.views.generic.simple import direct_to_template
from django.shortcuts import get_object_or_404, get_list_or_404
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.http import HttpResponseRedirect
from darkfraud.blog.models import Category, Tag, Post, Comment
from darkfraud.menu.models import Menu

from django import forms
from django.shortcuts import render_to_response
from django.contrib.auth.forms import UserCreationForm

def home(request):
    menu = Menu.objects.all().order_by('id')
    posts = Post.objects.filter(status = 1).order_by('-pub_date')
    categories = Category.objects.all()
    tags = Tag.objects.all()
    arhive = Post.objects.dates('pub_date', 'month')
    
    paginator = Paginator(posts, 10)
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1
    try:
        posts = paginator.page(page)
    except (EmptyPage, InvalidPage):
        posts = paginator.page(paginator.num_pages)
    
    return direct_to_template(request, 'blog/home.html', locals())
    
def category(request, slug):
    menu = Menu.objects.all()
    category = get_object_or_404(Category, slug=slug)
    posts = Post.objects.filter(categories = category, status = 1).order_by('-pub_date')
    categories = Category.objects.all()
    tags = Tag.objects.all()
    arhive = Post.objects.dates('pub_date', 'month')
    
    paginator = Paginator(posts, 10)
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1
    try:
        posts = paginator.page(page)
    except (EmptyPage, InvalidPage):
        posts = paginator.page(paginator.num_pages)
    
    return direct_to_template(request, 'blog/home.html', locals())
    
def tag(request, slug):
    menu = Menu.objects.all()
    tag = get_object_or_404(Tag, slug=slug)
    posts = Post.objects.filter(tags = tag, status = 1).order_by('-pub_date')
    categories = Category.objects.all()
    tags = Tag.objects.all()
    arhive = Post.objects.dates('pub_date', 'month')
    
    paginator = Paginator(posts, 10)
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1
    try:
        posts = paginator.page(page)
    except (EmptyPage, InvalidPage):
        posts = paginator.page(paginator.num_pages)
    
    return direct_to_template(request, 'blog/home.html', locals())
    
def post(request, year, month, day, slug):
    menu = Menu.objects.all()
    date_stamp = time.strptime(year+month+day, "%Y%m%d")
    pub_date = datetime.date(*date_stamp[:3])
    post = get_object_or_404(Post, pub_date__year=pub_date.year, pub_date__month=pub_date.month, pub_date__day=pub_date.day, slug=slug, status=1)
    categories = Category.objects.all()
    tags = Tag.objects.all()
    arhive = Post.objects.dates('pub_date', 'month')
    coments = Comment.objects.filter(post=post).order_by('-pub_date')
    if request.POST:
        comment_text = request.POST['text_comment']
        if len(comment_text)<3: return HttpResponseRedirect(request.path)
        author = request.user
        post_id = post
        db = Comment(status=1, comment=comment_text, author=author, post=post_id, pub_date=datetime.datetime.now())
        db.save()
        '''
        send_mail(
            'Новый коментарий',
            db.comment,
            'darkfraud@gmail.com',
            ['darkfraud@gmail.com'],
        )
        '''
        return HttpResponseRedirect(request.path+'#comment')
    return direct_to_template(request, 'blog/post.html', locals())
    
def arhive(request, year, month):
    menu = Menu.objects.all()
    date_stamp = time.strptime(year+month+str(12), "%Y%m%d")
    pub_date = datetime.date(*date_stamp[:3])
    posts = Post.objects.filter(status=1, pub_date__year=pub_date.year, pub_date__month=pub_date.month)
    categories = Category.objects.all()
    tags = Tag.objects.all()
    arhive = Post.objects.dates('pub_date', 'month')
    
    paginator = Paginator(posts, 10)
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1
    try:
        posts = paginator.page(page)
    except (EmptyPage, InvalidPage):
        posts = paginator.page(paginator.num_pages)
    
    return direct_to_template(request, 'blog/home.html', locals())
    
def register(request):
    menu = Menu.objects.all()
    form = UserCreationForm()
    if request.method == 'POST':
        data = request.POST.copy()
        form = UserCreationForm(data)
        if form.is_valid():
            new_user = form.save(data)
            '''
            send_mail(
                'Новый пользователь',
                new_user,
                'darkfraud@gmail.com',
                ['darkfraud@gmail.com'],
            )
            '''
            return HttpResponseRedirect("/accounts/login/")
    else:
        data, errors = {}, {}
    return direct_to_template(request, 'registration/register.html', locals())
    
def profile(request):
    return HttpResponseRedirect('/')
    
def search(request):
    # Наполнители
    menu = Menu.objects.all()
    posts = Post.objects.filter(status = 1).order_by('-pub_date')
    categories = Category.objects.all()
    tags = Tag.objects.all()
    arhive = Post.objects.dates('pub_date', 'month')
    # Поиск
    query = request.GET.get('q', '')
    if query:
        qset = (
            Q(title__icontains=query) |
            Q(content__icontains=query)
        )
        posts = Post.objects.filter(qset).distinct()
    # Пагинатор
    paginator = Paginator(posts, 10)
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1
    try:
        posts = paginator.page(page)
    except (EmptyPage, InvalidPage):
        posts = paginator.page(paginator.num_pages)
    
    return direct_to_template(request, 'blog/home.html', locals())

templates/blog/home.html
{% extends "base.html" %}

{% block menuTop %}
    {% include "menu/menu_top.html" %}
{% endblock %}

{% block menuLeft %}
    {% include "menu/menu_left.html" %}
{% endblock %}

{% block content %}
    {% for post in posts.object_list %}
                <div class="hat">{{ post.title }}</div>
                <div class="blockText">
                    {{ post.content|safe|truncatewords_html:100 }}
                    <div style="text-align:center; margin-bottom:5px;">
                        Добавил: {{ post.author }} Дата: {{ post.pub_date }}<br />
                        Раздел: {% for cat in post.categories.all %}<a href="/category/{{ cat.slug }}/">{{ cat.title }}</a> {% endfor %}<br />
                        Теги: {% for tag in post.tags.all %}<a href="/tag/{{ tag.slug }}/">{{ tag.title }}</a> {% endfor %}
                    </div>
                    <a class="submit" href="/post/{{ post.pub_date|date:'Y/m/d' }}/{{ post.slug }}/#comment">Коментарии</a>
                    <a class="submit" href="/post/{{ post.pub_date|date:'Y/m/d' }}/{{ post.slug }}/">Подробнее</a>
                </div>
    {% endfor %}
    {% if posts.object_list %}
        <div class="pagination">
            <span class="step-links">
                {% if posts.has_previous %}
                <a href="?page={{ posts.previous_page_number }}">Назад</a>
                {% endif %}
                <span class="current">
                    Страница {{ posts.number }} из {{ posts.paginator.num_pages }}.
                </span>
                {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}">Вперед</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% endblock %}

templates/blog/menu_left.html
                <div class="hat">Разделы</div>
                <div class="small_block">
                    <div style="margin-left:30px;">
                    {% for category in categories %}
                        <a href="/category/{{ category.slug }}/">{{ category.title }}</a> ({{ category.post_set.all.count }})<br />
                    {% endfor %}
                    </div>
                </div>
                <div class="hat">Теги</div>
                <div class="small_block" style="text-align: justify;">
                    <div id="tagcloud">
                    {% for tag in tags %}
                        <a href="/tag/{{ tag.slug }}/" rel="{{ tag.post_set.all.count }}">{{ tag.title }}</a>
                    {% endfor %}
                    </div>
                </div>
                <div class="hat">Архив</div>
                <div class="small_block">
                    <div style="margin-left:30px;">
                    {% for arhiv in arhive reversed %}
                    <a href="/arhive/{{ arhiv|date:"Y/m/" }}">{{ arhiv|date:"Y F" }}</a><br />
                    {% endfor %}
                    </div>
                </div>

templates/blog/post.html
{% extends "base.html" %}

{% block title %}Блог Кропотова Александра [Веб разработка / Web Developer] | {{ post.title }}{% endblock %}

{% block menuTop %}
    {% include "menu/menu_top.html" %}
{% endblock %}

{% block menuLeft %}
    {% include "menu/menu_left.html" %}
{% endblock %}

{% block content %}
                <div class="hat">{{ post.title }}</div>
                <div class="blockText">
                    {{ post.content|safe }}
                    <div style="text-align:center; margin-bottom:5px;">
                        Добавил: {{ post.author }} Дата: {{ post.pub_date }}<br />
                        Раздел: {% for cat in post.categories.all %}<a href="/category/{{ cat.slug }}/">{{ cat.title }}</a> {% endfor %}<br />
                        Теги: {% for tag in post.tags.all %}<a href="/tag/{{ tag.slug }}/">{{ tag.title }}</a> {% endfor %}
                    </div>
                </div>
                <a name="comment">&nbsp;</a>
                {% for comment in coments reversed %}
                <div class="commentBlock">
                    {{ comment.author }} {{ comment.pub_date }}<br />
                    <p>{{ comment.comment }}</p>
                </div>
                {% endfor %}
                {% if user.is_authenticated %}
                <p>
                <form action="" method="POST">{% csrf_token %}
                    <textarea rows="10" cols="60" name="text_comment"></textarea><br />
                    <input type="submit" value="Коментим">
                </form>
                </p>
                {% else %}
                <p><a class="submit" href="/accounts/login/">Чтобы коментировать нужно авторизироваться.</a></p>
                {% endif %}
    
{% endblock %}